/**
 * Bash completion script generator
 */

import type { CompletionGenerator, CommandDef, ArgDef, OptionDef } from './types.js';

export class BashGenerator implements CompletionGenerator {
  readonly shell = 'bash' as const;

  generate(commands: CommandDef[]): string {
    const lines: string[] = [
      '# Bash completion for speclife',
      '# Generated by speclife completion bash',
      '',
      '_speclife() {',
      '  local cur prev words cword',
      '  _init_completion || return',
      '',
      '  local commands="' + commands.map(c => c.name).join(' ') + '"',
      '',
      '  if [[ $cword -eq 1 ]]; then',
      '    COMPREPLY=($(compgen -W "$commands" -- "$cur"))',
      '    return',
      '  fi',
      '',
      '  local cmd="${words[1]}"',
      '',
      '  case "$cmd" in',
    ];

    for (const cmd of commands) {
      lines.push(...this.generateCommandCase(cmd));
    }

    lines.push('  esac');
    lines.push('}');
    lines.push('');
    lines.push('complete -F _speclife speclife');
    lines.push('');

    return lines.join('\n');
  }

  getInstallInstructions(): string {
    return `# Add to your ~/.bashrc or ~/.bash_profile:
speclife completion bash >> ~/.bashrc
source ~/.bashrc

# Or install system-wide (requires sudo):
speclife completion bash | sudo tee /etc/bash_completion.d/speclife`;
  }

  private generateCommandCase(cmd: CommandDef): string[] {
    const lines: string[] = [];
    lines.push(`    ${cmd.name})`);

    if (cmd.subcommands && cmd.subcommands.length > 0) {
      lines.push('      if [[ $cword -eq 2 ]]; then');
      lines.push(`        COMPREPLY=($(compgen -W "${cmd.subcommands.map(s => s.name).join(' ')}" -- "$cur"))`);
      lines.push('        return');
      lines.push('      fi');
      lines.push('      local subcmd="${words[2]}"');
      lines.push('      case "$subcmd" in');

      for (const sub of cmd.subcommands) {
        lines.push(`        ${sub.name})`);
        lines.push(...this.generateArgCompletion(sub.args ?? [], sub.options ?? [], 6));
        lines.push('          ;;');
      }

      lines.push('      esac');
    } else {
      lines.push(...this.generateArgCompletion(cmd.args ?? [], cmd.options ?? [], 4));
    }

    lines.push('      ;;');
    return lines;
  }

  private generateArgCompletion(args: ArgDef[], options: OptionDef[], indent: number): string[] {
    const pad = ' '.repeat(indent);
    const lines: string[] = [];
    const optionWords = options.flatMap(o => [o.short, o.long].filter(Boolean)).join(' ');

    if (options.length > 0) {
      lines.push(`${pad}case "$prev" in`);
      for (const opt of options.filter(o => o.takesValue)) {
        const pattern = [opt.short, opt.long].filter(Boolean).join('|');
        lines.push(`${pad}  ${pattern})`);
        lines.push(...this.generateValueCompletion(opt, indent + 4));
        lines.push(`${pad}    return`);
        lines.push(`${pad}    ;;`);
      }
      lines.push(`${pad}esac`);
    }

    lines.push(`${pad}if [[ "$cur" == -* ]]; then`);
    lines.push(`${pad}  COMPREPLY=($(compgen -W "${optionWords}" -- "$cur"))`);
    lines.push(`${pad}  return`);
    lines.push(`${pad}fi`);

    for (const arg of args) {
      if (arg.completion === 'static' && arg.staticValues) {
        lines.push(`${pad}COMPREPLY=($(compgen -W "${arg.staticValues.join(' ')}" -- "$cur"))`);
        break;
      } else if (arg.completion === 'file') {
        lines.push(`${pad}COMPREPLY=($(compgen -f -- "$cur"))`);
        break;
      } else if (arg.completion === 'directory') {
        lines.push(`${pad}COMPREPLY=($(compgen -d -- "$cur"))`);
        break;
      }
    }

    return lines;
  }

  private generateValueCompletion(opt: OptionDef, indent: number): string[] {
    const pad = ' '.repeat(indent);
    if (opt.valueCompletion === 'static' && opt.staticValues) {
      return [`${pad}COMPREPLY=($(compgen -W "${opt.staticValues.join(' ')}" -- "$cur"))`];
    } else if (opt.valueCompletion === 'file') {
      return [`${pad}COMPREPLY=($(compgen -f -- "$cur"))`];
    } else if (opt.valueCompletion === 'directory') {
      return [`${pad}COMPREPLY=($(compgen -d -- "$cur"))`];
    }
    return [];
  }
}
