# SpecLife Release Workflow
# Automatically creates GitHub releases when version changes are detected
# Triggered by version bump in package.json (from /speclife land)

name: Create Release

on:
  push:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.check.outputs.changed }}
      new_version: ${{ steps.check.outputs.version }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Check for version change
        id: check
        run: |
          # Get version from current commit
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          
          # Get version from previous commit
          git checkout HEAD~1 -- package.json 2>/dev/null || true
          PREV_VERSION=$(node -p "require('./package.json').version" 2>/dev/null || echo "0.0.0")
          git checkout HEAD -- package.json
          
          echo "Previous version: $PREV_VERSION"
          echo "Current version: $CURRENT_VERSION"
          
          if [ "$CURRENT_VERSION" != "$PREV_VERSION" ]; then
            echo "Version changed: $PREV_VERSION -> $CURRENT_VERSION"
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "version=v$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            echo "No version change"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  release:
    needs: check-version
    runs-on: ubuntu-latest
    if: needs.check-version.outputs.version_changed == 'true'
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create and push tag
        run: |
          VERSION="${{ needs.check-version.outputs.new_version }}"
          echo "Creating tag: $VERSION"
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "$VERSION"
          git push origin "$VERSION"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.check-version.outputs.new_version }}
          generate_release_notes: true
          body: |
            ## What's Changed
            
            See the [full changelog](https://github.com/${{ github.repository }}/compare/.../${{ needs.check-version.outputs.new_version }}) for details.

  # Optional: Add publish job for npm/other registries
  # Uncomment and configure as needed
  #
  # publish:
  #   needs: [check-version, release]
  #   if: ${{ always() && needs.release.result == 'success' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #         registry-url: 'https://registry.npmjs.org'
  #     - run: npm ci
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
